#!/usr/bin/env bash
# One-command bootstrap for a fresh machine.
#
#   git clone <repo> && cd claude-swap/deploy && ./setup.sh
#
# Everything compose needs is derived from the machine it runs on, so the same
# clone works for any user on any host without hand-editing anything. Safe to
# re-run: an existing .env is updated in place and its token is preserved.
set -euo pipefail

# --config-only: derive and write .env, then stop. Useful for inspecting what
# this machine resolves to, for CI, and for testing the fresh-machine path
# without building or touching a running stack.
CONFIG_ONLY=0
for arg in "$@"; do
  case "${arg}" in
    --config-only) CONFIG_ONLY=1 ;;
    -h|--help)
      sed -n '2,10p' "$0" | sed 's/^# \{0,1\}//'
      echo
      echo "Usage: ./setup.sh [--config-only]"
      exit 0 ;;
    *) echo "setup.sh: unknown option '${arg}' (try --help)" >&2; exit 2 ;;
  esac
done

cd "$(dirname "$(readlink -f "$0")")"

say()  { printf '\033[1m%s\033[0m\n' "$*"; }
info() { printf '  %s\n' "$*"; }
warn() { printf '  \033[33m! %s\033[0m\n' "$*" >&2; }
die()  { printf '\033[31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

# -- preflight ---------------------------------------------------------------
say "Checking prerequisites"

[ "$(id -u)" -ne 0 ] || die "do not run as root — the containers run as your own
  uid so files written into your home keep your ownership, and claude-swap
  refuses to run as root anyway."

command -v docker >/dev/null 2>&1 || die "docker is not installed."
docker info >/dev/null 2>&1 || die "cannot talk to the Docker daemon.
  Either it is not running, or you are not in the 'docker' group:
      sudo usermod -aG docker \"\$USER\"   # then log out and back in"
docker compose version >/dev/null 2>&1 || die "the docker compose plugin is missing."
info "docker $(docker version -f '{{.Server.Version}}' 2>/dev/null || echo '?') ok"

# A bind mount whose source path contains a space, or a home under a symlink,
# resolves differently inside the container than the user expects.
case "${HOME}" in
  *" "*) die "\$HOME ('${HOME}') contains a space; the bind mount will not work." ;;
esac
real_home=$(readlink -f "${HOME}")
if [ "${real_home}" != "${HOME}" ]; then
  warn "\$HOME is a symlink to ${real_home}; using the resolved path so the"
  warn "container and the host agree on one location."
fi

# -- derive the machine's values ---------------------------------------------
say "Deriving configuration for this machine"

HOST_UID=$(id -u)
HOST_GID=$(id -g)
HOST_HOME=${real_home}

# Prefer the system zone over a hardcoded one so logs and reset times read
# correctly wherever this is installed.
if [ -r /etc/timezone ]; then
  TZ=$(cat /etc/timezone)
elif command -v timedatectl >/dev/null 2>&1; then
  TZ=$(timedatectl show -p Timezone --value 2>/dev/null || echo UTC)
elif [ -L /etc/localtime ]; then
  TZ=$(readlink -f /etc/localtime | sed 's|.*/zoneinfo/||')
else
  TZ=UTC
fi
[ -n "${TZ}" ] || TZ=UTC

info "uid:gid = ${HOST_UID}:${HOST_GID}"
info "home    = ${HOST_HOME}"
info "timezone= ${TZ}"

# -- token: generate once, then preserve -------------------------------------
# Re-running setup must not rotate the token, or every run would invalidate the
# cookie already pinned in the browser.
existing_token=""
if [ -f .env ]; then
  existing_token=$(sed -n 's/^CSWAP_WEB_TOKEN=//p' .env | head -1)
fi
if [ -n "${existing_token}" ]; then
  CSWAP_WEB_TOKEN=${existing_token}
  info "token   = (preserved from existing .env)"
else
  CSWAP_WEB_TOKEN=$(python3 -c 'import secrets; print(secrets.token_urlsafe(24))' 2>/dev/null \
    || head -c 18 /dev/urandom | base64 | tr -d '=+/')
  info "token   = (generated)"
fi

# Preserve a tick interval the user may have tuned.
CSWAP_TICK_S=15
if [ -f .env ]; then
  prev_tick=$(sed -n 's/^CSWAP_TICK_S=//p' .env | head -1)
  [ -n "${prev_tick}" ] && CSWAP_TICK_S=${prev_tick}
fi

# -- write .env --------------------------------------------------------------
say "Writing .env"
umask 077                      # created 0600 from the start, never briefly world-readable
cat > .env <<EOF
# Generated by setup.sh for this machine. Safe to re-run; the token is preserved.
# Machine-specific and secret — gitignored, never commit.

HOST_UID=${HOST_UID}
HOST_GID=${HOST_GID}

# Must be the host home directory. It is bind-mounted at this IDENTICAL path so
# every path claude-swap derives resolves to the same file the host sees.
HOST_HOME=${HOST_HOME}

TZ=${TZ}

# Seconds between autoswitch evaluations. autoswitch.intervalSeconds does NOT
# apply here: 'cswap auto --once' evaluates once and returns, so the interval
# belongs to the loop that drives it.
CSWAP_TICK_S=${CSWAP_TICK_S}

# Dashboard token. Only read when auth is on (CSWAP_WEB_NO_AUTH=0 in
# docker-compose.yml). Pinned to a SameSite=Strict cookie after the first visit.
CSWAP_WEB_TOKEN=${CSWAP_WEB_TOKEN}
EOF
chmod 600 .env
info ".env written (mode $(stat -c %a .env))"

if [ "${CONFIG_ONLY}" -eq 1 ]; then
  say "Stopping here (--config-only)"
  exit 0
fi

# -- host shim ---------------------------------------------------------------
say "Installing the host 'cswap' command"
shim_target=$(readlink -f ./cswap-host)
bindir="${HOME}/.local/bin"
mkdir -p "${bindir}"
if [ -e "${bindir}/cswap" ] && [ ! -L "${bindir}/cswap" ]; then
  warn "${bindir}/cswap exists and is not a symlink — leaving it alone."
  warn "Run the CLI as: ${shim_target}"
elif [ "$(readlink -f "${bindir}/cswap" 2>/dev/null)" = "${shim_target}" ]; then
  info "already installed at ${bindir}/cswap"
else
  ln -sf "${shim_target}" "${bindir}/cswap"
  info "linked ${bindir}/cswap -> ${shim_target}"
fi
case ":${PATH}:" in
  *":${bindir}:"*) ;;
  *) warn "${bindir} is not on your PATH; add it to use 'cswap' directly." ;;
esac

# -- build and start ---------------------------------------------------------
say "Building the image from source"
docker compose build

say "Starting the stack"
docker compose up -d

# -- verify ------------------------------------------------------------------
say "Verifying"
ok=1
for _ in $(seq 1 30); do
  if [ "$(docker inspect -f '{{.State.Health.Status}}' cswap-web 2>/dev/null)" = healthy ]; then
    ok=0; break
  fi
  sleep 2
done
if [ "${ok}" -eq 0 ]; then
  info "dashboard  http://127.0.0.1:8787/  (healthy)"
else
  warn "cswap-web did not report healthy in 60s. Check: docker compose logs web"
fi

accounts=$(docker exec cswap-web cswap list --json 2>/dev/null \
  | python3 -c 'import sys,json;print(len(json.load(sys.stdin).get("accounts",[])))' 2>/dev/null || echo "?")
info "accounts managed: ${accounts}"

say "Done"
if [ "${accounts}" = "0" ]; then
  cat <<'EOF'
  No accounts yet. Log into Claude Code, then:

      cswap add                       # repeat for each account

  Restoring onto a new machine instead? Copy your export across and:

      cswap import backup.cswap
EOF
else
  echo "      cswap list        # accounts and usage"
  echo "      cswap export ~/cswap-backup.cswap   # take a backup you can restore anywhere"
fi
